language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
  - DJANGO_VERSION=1.11.5
# command to run tests
script:
  - python propalyzer_site/manage.py test
  
# safelist
branches:
  only:
  - ci-test
